### ISSUE TITLE
SRMI-dev版本无法使用替换后的d3d11.dll进入dev模式

### ISSUE THREAD

**Issue by RovingAimer** [StarBobis/MigotoModTool#1]
如题，SRMI-dev版本无法使用替换后的d3d11.dll进入dev模式，替换dll后进入游戏会与gameplay版表现一致，无法dump和切换ib，且没有dev的UI界面，因此也无法进行mod逆向

[SRMI](https://github.com/SilentNightSound/SR-Model-Importer)

**Comment by StarBobis** [comment]
1.如需使用Dump功能，确保使用工具附带的3Dmigoto-Armor版本的Dev版本的d3d11.dll替换你原本SRMI中的d3d11.dll。
2.3Dmigoto-Armor的Dev版本的d3d11.dll默认会关闭Hunting，需要按小键盘0键打开Hunting界面，也就是绿字界面。
3.3Dmigoto-Armor的Play版和PlayNoWarning版本从代码层面关闭了Hunting功能，无法打开绿字，如有Dump需求请使用Dev版本的d3d11.dll
4.如需进行Dump式Mod逆向，确保将d3dx.ini中的track_textures_update设为1，这个值只有设为1时才会开启Dump Mod后的IB的Hash值显示功能。

**Comment by RovingAimer** [comment]
感谢解答，已正确解析出实际绘制的IB，但是目前报错无法提取模型
`IB Info: 000010-ib=150fbb90-vs=1cc1976fc9a7b700` 
通过ib进行提取，在配置中尝试了所有提取类型选项，也尝试了重新计算TANGENT选项的组合，无法提取，报错log
`2024-06-02 12:36:13,811 INFO [default] Start to parse all pointlist vb file to detect possible d3d11Element type.
2024-06-02 12:36:13,811 INFO [default] --------------------------------------------------------------------
......
 省略
2024-06-02 12:36:13,814 INFO [default] --------------------------------------------------------------------
2024-06-02 12:36:13,841 INFO [default] Parsing pointlist index: 000009
2024-06-02 12:36:13,843 INFO [default] Start to parse pointlist FileNameList. 
2024-06-02 12:36:13,844 INFO [default] Parse pointlist elementlist over.
2024-06-02 12:36:13,845 INFO [default] Parse pointlist elementlist over.
2024-06-02 12:36:13,846 INFO [default] Parse pointlist elementlist over.
2024-06-02 12:36:13,848 INFO [default] [Error]:Can't find matchPointlistIndex, Please try force pointlist index.`
[选择auto配置下的log文件](https://github.com/user-attachments/files/15524195/20240602T123607.log)

**Comment by StarBobis** [comment]
> 感谢解答，已正确解析出实际绘制的IB，但是目前报错无法提取模型 `IB Info: 000010-ib=150fbb90-vs=1cc1976fc9a7b700` 通过ib进行提取，在配置中尝试了所有提取类型选项，也尝试了重新计算TANGENT选项的组合，无法提取，报错log `2024-06-02 12:36:13,811 INFO [default] Start to parse all pointlist vb file to detect possible d3d11Element type. 2024-06-02 12:36:13,811 INFO [default] -------------------------------------------------------------------- ...... 省略 2024-06-02 12:36:13,814 INFO [default] -------------------------------------------------------------------- 2024-06-02 12:36:13,841 INFO [default] Parsing pointlist index: 000009 2024-06-02 12:36:13,843 INFO [default] Start to parse pointlist FileNameList. 2024-06-02 12:36:13,844 INFO [default] Parse pointlist elementlist over. 2024-06-02 12:36:13,845 INFO [default] Parse pointlist elementlist over. 2024-06-02 12:36:13,846 INFO [default] Parse pointlist elementlist over. 2024-06-02 12:36:13,848 INFO [default] [Error]:Can't find matchPointlistIndex, Please try force pointlist index.` [选择auto配置下的log文件](https://github.com/user-attachments/files/15524195/20240602T123607.log)

1.如果需要从游戏的Dump文件里逆向提取Mod的话，必须手动指定要逆向提取的类型，这个类型可以在正常提取此Mod对应原始模型后output文件夹中生成的tmp.json中查看，Auto只能在正常提取原始模型时生效，不能在逆向提取时自动判断类型。
2.如果需要逆向提取Mod，在最新版中按钮的位置已发生改变，你需要按这个[提取Mod模型]按钮来提取逆向Mod，而不是正常的[提取模型按钮]：
![image](https://github.com/StarBobis/MigotoModTool/assets/151726114/9f047094-a885-4289-b8ef-0bba54956157)
