### ISSUE TITLE
模型导出乱码

### ISSUE THREAD

**Issue by hiiii65** [StarBobis/MigotoModTool#2]
![7B0A503275DC57AFFEA163BD50985567](https://github.com/StarBobis/MigotoModTool/assets/76000500/d2edb8bd-656e-4b78-837c-0a645c1ee995)

MMT 1.0.1.3
3Dmigoto GIMI V7.0 (development)
Blender 3.6.12
MMT blender plugin 1.0.0.9

**Comment by hiiii65** [comment]
blender内完成的步骤：

用插件4步清理模型
L选择关联的点
分离选择
删除顶点组
缩小并合并
通过插件导出

**Comment by StarBobis** [comment]
图片看起来像是缺少ShaderCheck，请检查你的d3dx.ini是否添加鸣潮的global check，参考如下：

[ShaderOverride_CSOverrides1]
hash = 1ff924db9d4048d1
run = CommandListCheckCS

[ShaderOverride_CSOverrides2]
hash = 4d0760c2c7406824
run = CommandListCheckCS

[CommandListCheckCS]
if $costume_mods
  checktextureoverride = cs-cb0
  checktextureoverride = cs-cb1
  checktextureoverride = cs-cb2
  checktextureoverride = cs-t0
  checktextureoverride = cs-t1
  checktextureoverride = cs-t2
  checktextureoverride = cs-t3
  checktextureoverride = cs-t4
  checktextureoverride = cs-t5
  checktextureoverride = cs-t6
  checktextureoverride = cs-u0
  checktextureoverride = cs-u1
endif

[ShaderRegexEnableTextureOverrides]
shader_model = vs_4_0 vs_4_1 vs_5_0 ps_4_0 ps_4_1 ps_5_0 
run = CommandListSkin

[CommandListSkin]
if $costume_mods
	checktextureoverride = vs-t0
	checktextureoverride = vs-t1
	checktextureoverride = vs-t2
	checktextureoverride = vb0
	checktextureoverride = vb1
	checktextureoverride = vb2
	checktextureoverride = vb3
	checktextureoverride = vb4
	checktextureoverride = ib
endif

**Comment by 1309994837** [comment]
直接粘贴进去不需要换掉什么嘛？

**Comment by StarBobis** [comment]
> 直接粘贴进去不需要换掉什么嘛？

只是参考，并不能直接替换进去，你需要搞懂d3dx.ini的运作方式，才知道具体如何替换。

**Comment by 1309994837** [comment]
![ZHQD{PH~M`WW`F1_13P{(V](https://github.com/StarBobis/MigotoModTool/assets/104332005/9a81f980-dcff-493d-be8d-a1cdb4175e25)

我在blender里右键做完了4步，然后没有修改东西直接一键导出，出现了这个情况

**Comment by 1309994837** [comment]
emm，好费解

**Comment by hiiii65** [comment]
我也是

**Comment by StarBobis** [comment]
> ![ZHQD{PH~MWWF1_13P{(V](https://private-user-images.githubusercontent.com/104332005/335967542-9a81f980-dcff-493d-be8d-a1cdb4175e25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NzA5MzcsIm5iZiI6MTcxNzQ3MDYzNywicGF0aCI6Ii8xMDQzMzIwMDUvMzM1OTY3NTQyLTlhODFmOTgwLWRjZmYtNDkzZC1iZThkLWExY2RiNDE3NWUyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQwMzEwMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMWM1ZGMxMmU1OWI1YWMyMzdjNWZiYzAzNTAyMWU1YzUyNThmZmYyMGFjZDI2YzVmNWJlOTUxMzE1YTg3NWNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zXe114m9It9F_PGo1IbhFor7fcxUI3TQ8gacGboKW4g)
> 
> 我在blender里右键做完了4步，然后没有修改东西直接一键导出，出现了这个情况

使用最新版本再试试，之前的一个版本使用TANGENT会导致顶点数量增加，就会出现这种情况，最新版本的1.0.1.4WW_Body使用COLOR代替TANGENT解决了这个问题

**Comment by 1309994837** [comment]
okk，已解决，0.o
