### ISSUE TITLE
导出的模型 导入blender出错

### ISSUE THREAD

**Issue by Kakatasky** [StarBobis/MigotoModTool#3]
MMT 1.0.1.9
3Dmigoto GIMI V7.0 (development)
Blender 3.6.2
MMT blender plugin 1.4.8
![image](https://github.com/StarBobis/MigotoModTool/assets/37499536/ea072293-c9a1-49d8-8d9e-0e73a965d824)
![image](https://github.com/StarBobis/MigotoModTool/assets/37499536/69b7b642-7024-4c7f-a950-2d608e7d245a)
另外尝试WW_body 直接无法导入blender
![image](https://github.com/StarBobis/MigotoModTool/assets/37499536/2a502631-38af-4e27-8855-6dc33f6925a0)

**Comment by StarBobis** [comment]
https://github.com/StarBobis/MigotoModTool/releases/tag/V1.0.2.1
我在最新的V1.0.2.1版本中加入了一个新的类型WW_ObjectType2，
你有空可以试试能不能用这个类型

**Comment by Kakatasky** [comment]
有用，感谢
