### ISSUE TITLE
无法在原神游戏中提取模型

### ISSUE THREAD

**Issue by Joker-2333** [StarBobis/MigotoModTool#4]
尝试了V1.0.3.2，V1.0.2.6，V1.0.2.4，V1.0.2.1四个版本，均无法在原神游戏中逆向提取模型，其他版本还未尝试，已使用3Dmigoto-Armor版本Dev版本d3d11.dll，已确认d3dx.ini中的track_textures_update设为1，导出后并未解析出实际绘制ib，显示为ib-vs
![20240614193832](https://github.com/StarBobis/MigotoModTool/assets/172789237/ddffa0f9-a9db-46cf-99b8-e79e67519201)

**Comment by StarBobis** [comment]
1.首先确保你使用的是MMT附带提供的Dev版本的dll，用它来替换你原本使用的d3d11.dll
![image](https://github.com/StarBobis/MigotoModTool/assets/151726114/6735caed-3eb4-4cfc-9a06-b16c8cda49a0)

2.其次确保你的d3dx.ini中关于track_texture_updates正确设为1，在ini文件中分号开头的配置被视为注释，是不生效的，确保你解开了注释。
![image](https://github.com/StarBobis/MigotoModTool/assets/151726114/bb812bee-2bf5-4843-b317-e93a413b81b7)

3.这两步完成之后，重新启动游戏，在你打了Mod的人物那里按小键盘0键来打开Hunting界面，再按一下小键盘的+号来重置当前Hunting界面，随后按下F8来dump模型

4.此时去你最新Dump出来的FrameAnalysis文件夹中，找到log.txt，搜索你游戏里按小键盘9键在Hunting界面复制的打了Mod的部位的IB，找到对应的数字索引，使用这个索引在FrameAnalysis文件夹中找到对应的索引-ib=，这时候ib=后面应该跟着一串hash值。

5.输入IB并使用逆向提取按钮：
![image](https://github.com/StarBobis/MigotoModTool/assets/151726114/36fa4239-5b53-4e52-bba9-c67e308e0bfb)

你的描述里显示你无法看到dump之后的ib=后面的hash值，那么请仔细检查，确保我说的第1和2步你准确操作无误。

此功能经过广泛测试非常稳定，一般都是因为自己配置不正确才会出现这种情况，请务必仔细检查自己的步骤是否完全正确。

**Comment by Joker-2333** [comment]
> 1.首先确保你使用的MMT附带提供的Dev版本dll，你可以使用它来替换你使用的d3d11.dll ![图像](https://private-user-images.githubusercontent.com/151726114/339788581-6735caed-3eb4-4cfc-9a06-b16c8cda49a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzM5MDgsIm5iZiI6MTcxODM3MzYwOCwicGF0aCI6Ii8xNTE3MjYxMTQvMzM5Nzg4NTgxLTY3MzVjYWVkLTNlYjQtNGNmYy05YTA2LWIxNmM4Y2RhNDlhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxNDAwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZmQxZGYyYjljOTcyMjFiZjA2OGU1ODVjYTA3NjVmNmE0ODI3NmM0MGZiYzk5YTY4OWJlOWY5ZmQxY2QzMjFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E64nuiBTQ5bNThxOzbTrzbO8V76Ac6GdSW9cC22eMUk)
> 
> 2.其次确保你的d3dx.ini中关于track_texture_updates正确设为1，在ini文件中分号开头的配置不符合注释，是不生效的，确保你解开了注释。 ![图像](https://private-user-images.githubusercontent.com/151726114/339788792-bb812bee-2bf5-4843-b317-e93a413b81b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzM5MDgsIm5iZiI6MTcxODM3MzYwOCwicGF0aCI6Ii8xNTE3MjYxMTQvMzM5Nzg4NzkyLWJiODEyYmVlLTJiZjUtNDg0My1iMzE3LWU5M2E0MTNiODFiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxNDAwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNzdhMzYyMjViZTlkY2RjNDk1N2VhNTAyNGZmMjA0ZTQ4NjA4MzRiNjU2NDYyMjg3ZWQyOGFkNzcxZGJjMzRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8VPiXy_S3jC9-U-XWH_PfLODiCck4PNyqwk_jTW1Yco)
> 
> 3.两只脚完成之后，重新启动游戏，在你打了Mod的人物那里按小键盘的0键来打开狩猎界面，再按一下小键盘的+号来重置当前狩猎界面，随后按F8来dump模型
> 
> 4.此时去你最新Dump出来的FrameAnalysis笔记本，找到log.txt，搜索你游戏里按小键盘9键在Hunting界面复制的打了Mod的部位的IB，找到对应的数字索引，使用这个索引在FrameAnalysis笔记本找到对应的索引-ib=，突然ib=后面应该跟着一串hash值。
> 
> 5.输入IB网页反向导出按钮： ![图像](https://private-user-images.githubusercontent.com/151726114/339789981-36fa4239-5b53-4e52-bba9-c67e308e0bfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzM5MDgsIm5iZiI6MTcxODM3MzYwOCwicGF0aCI6Ii8xNTE3MjYxMTQvMzM5Nzg5OTgxLTM2ZmE0MjM5LTViNTMtNGU1Mi1iYmE5LWM2N2UzMDhlMGJmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxNDAwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNGM2MDcyMWI0MjQ4ODlmYThhOTQxMzM5NzA0ZjNkZWVlOGM2M2M1ZjY2OGU1NDIxMjU2NDkyZDhmMjE2OWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RNZoVSn1z6HQqiUTmtM_VFEpPCkHPEP43y_H7_a97ws)
> 
> 你的描述里显示你无法看到dump之后的ib=后面的hash值，那么请仔细检查，确保我说的第1和2步你准确操作无误。
> 
> 为了避免出现这种情况，我们拒绝仔细检查自己的配置是否完全正确。

十分感谢，问题已解决，我应该删除track_texture_updates=1前面这该死的分号“；”

**Comment by StarBobis** [comment]
好的，那么issue关闭了
