### ISSUE TITLE
如何更改键位？我用的键盘没有小数字键盘。How do I change the keybits? The keyboard I use doesn't have a small numeric keypad.

### ISSUE THREAD

**Issue by gtuyate** [StarBobis/MigotoModTool#6]
How do I change the keybits? The keyboard I use doesn't have a small numeric keypad.

**Comment by StarBobis** [comment]
Open your d3dx.ini and go to [Hunting] section
![image](https://github.com/StarBobis/MigotoModTool/assets/151726114/8f6f1060-300d-4ffa-92d8-bcdde9528e92)
Go to keybinds part, and modify their bind keys.
![image](https://github.com/StarBobis/MigotoModTool/assets/151726114/8f2199ff-5a67-4189-9224-bbd75a20c0e2)

so how do you know which value should you replace there? 
for this question you should look 3Dmigoto's source code, see this link here:

[https://github.com/bo3b/3Dmigoto/blob/master/vkeys.h](https://github.com/bo3b/3Dmigoto/blob/master/vkeys.h)
![image](https://github.com/StarBobis/MigotoModTool/assets/151726114/7585beec-651e-4ddd-8b26-d0dd79838ea0)

So now you know every key's string in 3Dmigoto, now you can modify your key bind in d3dx.ini.

**Comment by StarBobis** [comment]
As all information provided and long time no reply, i think you already learned how to change key setting, so this issue close now, you're welcome to reopen it if you have other questions.
