### ISSUE TITLE
d3d11.dll

### ISSUE THREAD

**Issue by PaulJiang-123** [StarBobis/MigotoModTool#7]
我有两个问题 1.替换d3d11(DEV)后还是不能获取ib即使我让track_textures_update=1了 2.换了d3d11并dump之后 游戏就处于无限加载的情况(我用的Cultivation)
![image](https://github.com/StarBobis/MigotoModTool/assets/105531409/ceeda989-3e0c-4429-8d1e-4a5e9fe95e01)

**Comment by StarBobis** [comment]
> 1.替换d3d11(DEV)后还是不能获取ib即使我让track_textures_update=1了
检查你的d3d11.dll是不是3Dmigoto-Armor的Dev版本的d3d11.dll，其它人发布的d3d11.dll没有逆向dump的特性。
检查你的track_textures_update=1前面是否被分号;注释掉了，如果是则解开注释。

> 2.换了d3d11并dump之后 游戏就处于无限加载的情况(我用的Cultivation)

游戏处于无限加载是因为你Dump时间太长导致掉线，请把3Dmigoto和游戏都安装到固态硬盘，并升级你的电脑配置，机械硬盘玩不转3Dmigoto的。

**Comment by PaulJiang-123** [comment]
![屏幕截图 2024-07-09 141221](https://github.com/StarBobis/MigotoModTool/assets/105531409/1adf8bbd-f2c4-4263-86f0-83b51575efcb)

**Comment by StarBobis** [comment]
1.逆向提取模型的按钮在这里，并不是那个大的【提取模型】按钮：
![image](https://github.com/StarBobis/MigotoModTool/assets/151726114/0cb297a9-9de1-4802-94fb-5519df84bf7c)

2.MMT V1.0.4.8及以上版本已隐藏逆向提取功能，请去内部群解锁或者使用V1.0.4.7或之前的旧版本凑合使用，如果你有AGMG的ProModder权限我也可以送你一份。
